# -*- coding: utf-8 -*-
"""preprocess

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15o7nXtJccInMFU7Hu__ChfUr8FOIkxOs
"""

# @title preprocess
"""
Preprocessing script for UrbanFacade model
  - Parses XML annotations and polygons
  - Applies morphological operations and simplification
  - Generates segmentation masks and resizes images/masks
"""

# -------------------------------------------------------------------------
# Setting
# -------------------------------------------------------------------------
# Import libraries
import os
import re
import xml.etree.ElementTree as ET
import pandas as pd
import numpy as np
import cv2
import json
from shapely.geometry import Polygon
from tqdm import tqdm
from concurrent.futures import ProcessPoolExecutor, as_completed
from lxml import etree as ET

# Google Drive mount
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# Paths
base_dir = "/content/drive/MyDrive/Segmentation"
xml_dir = f"{base_dir}/Raw"
data_dir = f"{base_dir}/Raw"
resize_dir_image = os.path.join(base_dir, "Image")
resize_dir_mask  = os.path.join(base_dir, "Mask")

# Resize resolution
target_size = (1024, 1024)

# Classes
facade_classes = {
    "door": 1,
    "signboard_channel": 2,
    "signboard_front": 3,
    "signboard_side": 4,
    "signboard_stand": 5,
    "window_full_trp": 6,
    "window_non_trp": 7,
    "window_semi_trp": 8,
    "building": 9
}

# -------------------------------------------------------------------------
# XML Polygon Parsing
# -------------------------------------------------------------------------
def parse_polygon(points_str):
    points = points_str.split(';')
    return [(int(float(x)), int(float(y))) for x, y in (point.split(',') for point in points)]

# -------------------------------------------------------------------------
# Morphological operations
# -------------------------------------------------------------------------
def apply_morphological_operations_by_label(xml_file, kernel_size=5, iterations=2):
    tree = ET.parse(xml_file)
    root = tree.getroot()

    polygons_parent = root if root.tag == "image" else root.find(".//image")
    if polygons_parent is None:
        raise ValueError(f"{xml_file}: Cannot find image tage.")

    img_width = int(polygons_parent.get('width'))
    img_height = int(polygons_parent.get('height'))

    # Objects by label
    label_polygons = {}
    for polygon_tag in root.findall(".//polygon"):
        label = polygon_tag.attrib.get("label", "unknown")
        points_attr = polygon_tag.attrib.get("points", "")
        points = np.array([tuple(map(float, point.split(","))) for point in points_attr.split(";")], np.int32)
        label_polygons.setdefault(label, []).append(points)

    # Dilation & Closing
    new_label_polygons = {}
    for label, polygons in label_polygons.items():
        mask = np.zeros((img_height, img_width), dtype=np.uint8)
        for poly in polygons:
            cv2.fillPoly(mask, [poly], 255)
        kernel = np.ones((kernel_size, kernel_size), np.uint8)
        closed_mask = cv2.morphologyEx(cv2.dilate(mask, kernel, iterations=iterations),
                                       cv2.MORPH_CLOSE, kernel)
        contours, _ = cv2.findContours(closed_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        new_label_polygons[label] = [contour.squeeze() for contour in contours if len(contour) >= 3]

    # XML update
    for polygon_tag in polygons_parent.findall(".//polygon"):
        polygons_parent.remove(polygon_tag)
    for label, polygons in new_label_polygons.items():
        for poly in polygons:
            points_str = ";".join([f"{x},{y}" for x, y in poly])
            ET.SubElement(root, "polygon", {"points": points_str, "label": label})

    return tree

# -------------------------------------------------------------------------
# Object simplification
# -------------------------------------------------------------------------
def simplify_xml_in_memory(tree, tolerance=10):
    root = tree.getroot()
    for polygon_tag in root.findall(".//polygon"):
        points_attr = polygon_tag.attrib.get("points", "")
        points = [tuple(map(float, point.split(","))) for point in points_attr.split(";")]
        polygon = Polygon(points)
        simplified_polygon = polygon.simplify(tolerance)
        simplified_points_str = ";".join([f"{x:.2f},{y:.2f}" for x, y in simplified_polygon.exterior.coords])
        polygon_tag.set("points", simplified_points_str)
    return tree

# -------------------------------------------------------------------------
# Masking objects
# -------------------------------------------------------------------------
def create_mask(image_path, tree):
    image = cv2.imread(image_path)
    height, width, _ = image.shape
    mask = np.zeros((height, width), dtype=np.uint8)

    root = tree.getroot()

    for polygon in root.findall(".//polygon"):
        if polygon.get("label") == "building":
            points = parse_polygon(polygon.get("points"))
            cv2.fillPoly(mask, [np.array(points, dtype=np.int32)], facade_classes["building"])

    for polygon in root.findall(".//polygon"):
        label = polygon.get("label")
        if label != "building":
            points = parse_polygon(polygon.get("points"))
            class_id = facade_classes.get(label, 0)
            cv2.fillPoly(mask, [np.array(points, dtype=np.int32)], class_id)
    return mask

# -------------------------------------------------------------------------
# Main
# -------------------------------------------------------------------------
def main():
    xml_files = [f for f in os.listdir(data_dir) if f.endswith(".xml")]

    for file_name in tqdm(xml_files, desc="Processing files"):
        image_name = file_name.replace(".xml", "")
        image_path = os.path.join(data_dir, f"{image_name}.jpg")
        xml_path   = os.path.join(data_dir, file_name)

        image = cv2.imread(image_path)
        if image is None:
            print(f"Fail to load image: {image_path}")
            continue

        try:
            merged_tree = apply_morphological_operations_by_label(xml_path)
            simplified_tree = simplify_xml_in_memory(merged_tree, tolerance=10)

            mask = create_mask(image_path, simplified_tree)

            img_resized  = cv2.resize(image, target_size, interpolation=cv2.INTER_AREA)
            mask_resized = cv2.resize(mask, target_size, interpolation=cv2.INTER_NEAREST)

            cv2.imwrite(os.path.join(resize_dir_image, f"{image_name}_resize.jpg"), img_resized)
            cv2.imwrite(os.path.join(resize_dir_mask,  f"{image_name}_mask.png"), mask_resized)

        except Exception as e:
            print(f"Error - File: {file_name}\nError: {str(e)}")
            continue

if __name__ == "__main__":
    main()