# -*- coding: utf-8 -*-
"""train

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S67nayqmodNDcFevH799XxXZGIT7gJu6
"""

#@title train
"""
Training script for the UrbanFacade model
  - Loads preprocessed image-mask pairs
  - Defines ResNet-based decoder-encoder segmentation network
  - Implements training, validation, checkpointing, and metric evaluation
"""

# -------------------------------------------------------------------------
# Setting
# -------------------------------------------------------------------------
# Import libraries
!pip install -q albumentations mpld3

import os, sys, time, random, pickle, cv2, numpy as np, pandas as pd, matplotlib.pyplot as plt
import matplotlib.ticker as mticker
from tqdm import tqdm
import albumentations as A
from albumentations.pytorch import ToTensorV2
import torch, torch.nn as nn, torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, Subset
from torchvision.models import resnet50, ResNet50_Weights
from torch import amp
from IPython.display import display, HTML
import mpld3

# Google Drive mount
from google.colab import drive
drive.mount('/content/drive')

# Paths
base_dir   = "/content/drive/MyDrive/Segmentation"
train_dir  = os.path.join(base_dir, "Train")

image_dir = os.path.join(base_dir, "Image")
mask_dir  = os.path.join(base_dir, "Mask")

# Random seed
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

# Color palette
num_classes = 10

facade_colors = np.array([
    (0, 0, 0),        # background
    (0, 0, 255),      # door
    (0, 255, 0),      # signboard_channel
    (255, 0, 0),      # signboard_front
    (0, 255, 255),    # signboard_side
    (255, 0, 255),    # signboard_stand
    (255, 255, 0),    # window_full_trp
    (128, 0, 128),    # window_non_trp
    (0, 165, 255),    # window_semi_trp
    (128, 128, 128)   # building
], dtype=np.uint8)

def colorize(mask: np.ndarray) -> np.ndarray:
    return facade_colors[mask.clip(0, len(facade_colors)-1)]

# -------------------------------------------------------------------------
# Dataset
# -------------------------------------------------------------------------
class FacadeDataset(Dataset):
    def __init__(self, image_dir, mask_dir, transform=None):
        self.image_dir = image_dir
        self.mask_dir  = mask_dir
        self.transform = transform
        files = [f for f in os.listdir(image_dir) if f.lower().endswith(".jpg")]
        self.images = [f for f in sorted(files)]

    def __len__(self): return len(self.images)

    def __getitem__(self, idx):
        img_name = self.images[idx]
        stem = os.path.splitext(img_name)[0].replace("_resize", "")

        img_path  = os.path.join(self.image_dir, img_name)
        mask_path = os.path.join(self.mask_dir, f"{stem}_mask.png")

        if not os.path.exists(mask_path):
            raise FileNotFoundError(f"Mask not found: {mask_path}")

        image = cv2.cvtColor(cv2.imread(img_path), cv2.COLOR_BGR2RGB)
        mask  = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)

        if self.transform:
            aug = self.transform(image=image, mask=mask)
            image, mask = aug["image"], aug["mask"]

        return image, mask.long(), img_name

# -------------------------------------------------------------------------
# Model architecture
# -------------------------------------------------------------------------
class Decoder(nn.Module):
    def __init__(self, in_ch, skip_ch, out_ch):
        super().__init__()
        self.up = nn.ConvTranspose2d(in_ch, out_ch, 2, 2)
        self.conv = nn.Sequential(
            nn.Conv2d(out_ch+skip_ch, out_ch, 3, padding=1),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True)
        )
    def forward(self, x, skip):
        x = self.up(x)
        x = torch.cat([x, skip], dim = 1)
        return self.conv(x)

class FacadeResNet(nn.Module):
    def __init__(self, n_classes=num_classes):
        super().__init__()
        base = resnet50(weights=ResNet50_Weights.IMAGENET1K_V2)
        self.layer0 = nn.Sequential(base.conv1, base.bn1, base.relu, base.maxpool)
        self.layer1, self.layer2, self.layer3, self.layer4 = base.layer1, base.layer2, base.layer3, base.layer4
        self.up3 = Decoder(2048, 1024, 512)
        self.up2 = Decoder(512, 512, 256)
        self.up1 = Decoder(256, 256, 128)
        self.final = nn.Conv2d(128, n_classes, 1)

    def forward(self, x):
        s0 = self.layer0(x)
        s1 = self.layer1(s0)
        s2 = self.layer2(s1)
        s3 = self.layer3(s2)
        s4 = self.layer4(s3)
        d3 = self.up3(s4, s3)
        d2 = self.up2(d3, s2)
        d1 = self.up1(d2, s1)
        out = self.final(d1)
        return F.interpolate(out, size=x.shape[2:], mode="bilinear", align_corners=False)

# -------------------------------------------------------------------------
# Model checkpoint
# -------------------------------------------------------------------------
def save_checkpoint(epoch, model, optimizer, ckpt_dir):
    os.makedirs(ckpt_dir, exist_ok=True)
    save_path = os.path.join(ckpt_dir, f"epoch_{epoch+1}.pth")
    torch.save({
        'epoch': epoch,
        'model_state_dict': model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict()
    }, save_path)

def load_checkpoint(model, optimizer, ckpt_dir):
    if not os.path.exists(ckpt_dir):
        os.makedirs(ckpt_dir, exist_ok=True)
        return 0

    ckpts = sorted([f for f in os.listdir(ckpt_dir) if f.endswith(".pth")])
    if not ckpts:
        print("No checkpoint found. Generating a new checkpoint.")
        return 0

    latest_ckpt = os.path.join(ckpt_dir, ckpts[-1])
    ckpt = torch.load(latest_ckpt)
    model.load_state_dict(ckpt['model_state_dict'])
    optimizer.load_state_dict(ckpt['optimizer_state_dict'])
    start_epoch = ckpt['epoch']+1
    print(f"Resumed from {latest_ckpt} (epoch {start_epoch})")
    return start_epoch

# -------------------------------------------------------------------------
# Model metrics
# -------------------------------------------------------------------------
def model_metrics(hist):
    acc = np.diag(hist).sum()/hist.sum()
    iu = np.diag(hist)/(hist.sum(1)+hist.sum(0)-np.diag(hist)+1e-6)
    mean_iu = np.nanmean(iu)
    f1 = 2*np.diag(hist)/(hist.sum(1)+hist.sum(0)+1e-6)
    return acc, mean_iu, iu, f1

# -------------------------------------------------------------------------
# Loss function
# -------------------------------------------------------------------------
def dice_loss(logits, target, eps=1e-6):
    probs = F.softmax(logits, dim=1)
    target_oh = F.one_hot(target, num_classes=logits.shape[1]).permute(0, 3, 1, 2).float()
    inter = torch.sum(probs*target_oh, dim=(0, 2, 3))
    card  = torch.sum(probs+target_oh, dim=(0, 2, 3))
    dice = (2*inter+eps)/(card+eps)
    return 1-dice.mean()

# -------------------------------------------------------------------------
# Loss graph
# -------------------------------------------------------------------------
def loss_graph(x_data, val_loss_list, process_pkl, label="Loss"):
    cv_fig, cv_ax = plt.subplots(figsize=(10, 8))
    cv_ax.xaxis.set_major_locator(mticker.MaxNLocator(integer=True))
    cv_ax.set_xlabel("Epoch")
    cv_ax.set_ylabel("Validation Loss")

    (line,) = cv_ax.plot(x_data, val_loss_list, label=label, color="blue")
    cv_ax.legend()
    cv_ax.relim()
    cv_ax.autoscale_view()

    cv_graph_display = display(HTML(mpld3.fig_to_html(cv_fig)), display_id="cv_graph")

    with open(process_pkl, "wb") as f:
        pickle.dump((x_data, val_loss_list), f)
    cv_fig.savefig(os.path.join(train_dir, "Loss.png"))
    plt.close(cv_fig)

    return x_data, val_loss_list

# -------------------------------------------------------------------------
# Model train & evaluate
# -------------------------------------------------------------------------
scaler = amp.GradScaler(device="cuda")

def train(model, loader, opt, criterion, device, epoch=None, total_epochs=None):
    model.train()
    total = 0
    loop = tqdm(loader, desc=f"Training Epoch {epoch+1}/{total_epochs}" if epoch is not None else "Training", leave=True)
    for x,y,_ in loop:
        x,y = x.to(device), y.to(device)
        opt.zero_grad()

        with amp.autocast("cuda"):
          out  = model(x)
          loss = criterion(out,y)

        scaler.scale(loss).backward()
        scaler.step(opt)
        scaler.update()

        total += loss.item()*x.size(0)
    return total/len(loader.dataset)

def evaluate(model, loader, criterion, device, epoch=None, total_epochs=None):
    model.eval()
    hist = np.zeros((num_classes, num_classes))
    total_loss = 0
    n = 0
    loop = tqdm(loader, desc=f"Validating Epoch {epoch+1}/{total_epochs}" if epoch is not None else "Validating", leave=False)
    with torch.no_grad():
        for x,y,_ in loop:
            with amp.autocast("cuda"):
                out = model(x.to(device))
                loss = criterion(out, y.to(device))
            total_loss += loss.item()*x.size(0)
            n += x.size(0)
            pred = out.argmax(1).cpu().numpy()
            gt = y.numpy()
            mask = (gt>=0) & (gt<num_classes)
            hist += np.bincount(num_classes*gt[mask]+pred[mask], minlength=num_classes**2).reshape(num_classes, num_classes)
    iu = np.diag(hist)/(hist.sum(1)+hist.sum(0)-np.diag(hist)+1e-6)
    avg_loss = total_loss/max(n, 1)
    return avg_loss, np.nanmean(iu), hist

# -------------------------------------------------------------------------
# Main
# -------------------------------------------------------------------------
if __name__ == "__main__":
    # Loading GPU
    set_seed(42)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    torch.backends.cudnn.benchmark = True
    batch_size = 16
    epochs = 40

    # Loading graph
    x_data, val_loss_list = [], []
    process_pkl = os.path.join(train_dir, "Process.pkl")

    if os.path.exists(process_pkl):
        with open(process_pkl, "rb") as f:
            x_data, val_loss_list = pickle.load(f)
        print(f"Graph loaded. Resuming from epoch {len(x_data)}.")
    else:
        print("No graph found. Starting a new graph.")

    # Data augmentation
    transform = A.Compose([
        A.HorizontalFlip(p=0.5),
        A.RandomBrightnessContrast(p=0.5),
        A.HueSaturationValue(p=0.3),
        A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
        ToTensorV2()
    ])

    # Loading dataset
    ds = FacadeDataset(image_dir, mask_dir, transform)

    split_path = os.path.join(train_dir, "Split_Index.pkl")
    if os.path.exists(split_path):
        with open(split_path, "rb") as f:
            idx = pickle.load(f)
        print(f"Split indices loaded.")
    else:
        idx = np.random.permutation(len(ds))
        with open(split_path, "wb") as f:
            pickle.dump(idx, f)
        print(f"No split indicies found. Generating a new split indices.")

    n = int(0.8*len(idx))
    m = int(0.9*len(idx))
    train_ds, val_ds, test_ds = Subset(ds, idx[:n]), Subset(ds, idx[n:m]), Subset(ds, idx[m:])

    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True, num_workers=6, pin_memory=True, persistent_workers=True)
    val_loader = DataLoader(val_ds, batch_size=batch_size, shuffle=False, num_workers=6, pin_memory=True, persistent_workers=True)
    test_loader = DataLoader(test_ds, batch_size=batch_size, shuffle=False, num_workers=6, pin_memory=True, persistent_workers=True)

    # Initializing model
    model = FacadeResNet(n_classes=num_classes).to(device)
    opt = torch.optim.AdamW(model.parameters(), lr=1e-5, weight_decay=5e-2)
    criterion = dice_loss

    ckpt_path = os.path.join(train_dir, "Checkpoint.pth")
    start_epoch = load_checkpoint(model, opt, ckpt_path)

    # Save loss data
    loss_xlsx = os.path.join(train_dir, "Loss.xlsx")
    if os.path.exists(loss_xlsx):
        loss_df = pd.read_excel(loss_xlsx)
    else:
        loss_df = pd.DataFrame(columns=["epoch", "train_loss", "val_loss"])

    # Save visualization data
    viz_dir = os.path.join(train_dir, "Visualization")
    os.makedirs(viz_dir, exist_ok = True)
    viz_sel = os.path.join(viz_dir, "viz_selection.pkl")

    test_fnames = [ds.images[i] for i in idx[m:]]

    if os.path.exists(viz_sel):
        with open(viz_sel, "rb") as f:
            viz_samples = pickle.load(f)
        print(f"Loaded fixed visualization samples: {viz_samples}.")
    else:
        random.seed(10)
        viz_samples = random.sample(test_fnames, k = min(3, len(test_fnames)))
        with open(viz_sel, "wb") as f:
            pickle.dump(viz_samples, f)
        print(f"Generated new fixed visualization samples: {viz_samples}.")

    # Model training loop
    ckpt_dir = os.path.join(train_dir, "Checkpoint")
    os.makedirs(ckpt_dir, exist_ok=True)

    start_epoch = load_checkpoint(model, opt, ckpt_dir)

    for ep in range(start_epoch, epochs):
        tr = train(model, train_loader, opt, criterion, device, epoch=ep, total_epochs=epochs)
        val_loss, val_miou, hist = evaluate(model, val_loader, criterion, device, epoch=ep, total_epochs=epochs)

        x_data.append(ep+1)
        val_loss_list.append(val_loss)
        x_data, val_loss_list = loss_graph(x_data, val_loss_list, process_pkl)

        save_checkpoint(ep, model, opt, ckpt_dir)

        row = {"epoch": ep+1, "train_loss": float(tr), "val_loss": float(val_loss)}
        loss_df.loc[len(loss_df)] = row
        loss_df.to_excel(loss_xlsx, index=False)

        model.eval()
        with torch.no_grad():
            eval_tf = A.Compose([A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)), ToTensorV2()])
            for fn in viz_samples:
                img_path = os.path.join(image_dir, fn)
                orig = cv2.cvtColor(cv2.imread(img_path), cv2.COLOR_BGR2RGB)
                aug = eval_tf(image=orig)
                x = aug["image"].unsqueeze(0).to(device)

                logits = F.softmax(model(x), dim=1)[0].cpu().numpy()
                pred = logits.argmax(0)

                mask_path = os.path.join(mask_dir, fn.replace("_resize.jpg", "_mask.png"))
                gt = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)

                fig, axes = plt.subplots(1, 3, figsize=(14, 5))
                for ax, img, title in zip(
                    axes,
                    [orig, colorize(gt), colorize(pred)],
                    ["Original", "Ground Truth", "Prediction"]
                ):
                    ax.imshow(img)
                    ax.set_title(title, fontsize=12, pad=10)
                    ax.axis("off")

                img_id = os.path.splitext(fn)[0].replace("_resize", "")
                plt.subplots_adjust(top=0.88, wspace=0.05)
                out_png = os.path.join(viz_dir, f"viz_{img_id}_{ep+1}.png")
                plt.savefig(out_png, bbox_inches="tight")
                plt.close(fig)

    # Save final model
    chosen_epoch = int(input("Enter the epoch number to finalize the model: "))
    ckpt_path = os.path.join(ckpt_dir, f"epoch_{chosen_epoch}.pth")

    if os.path.exists(ckpt_path):
        ckpt = torch.load(ckpt_path)
        model.load_state_dict(ckpt['model_state_dict'])
        torch.save(model.state_dict(), os.path.join(train_dir, "UrbanFacade.pth"))
        print(f"Saved final model from epoch {chosen_epoch}.")
    else:
        print(f"No checkpoint for epoch {chosen_epoch}.")

    # Save model metrics
    _, miou, hist = evaluate(model, test_loader, criterion, device)
    acc, mean_iu, iu, f1 = model_metrics(hist)

    eps = 1e-6
    TP = np.diag(hist).astype(float)
    recall_c     = TP/(hist.sum(axis=1)+eps)
    precision_c  = TP/(hist.sum(axis=0)+eps)
    balanced_acc = float(np.nanmean(recall_c))
    precision    = float(np.nanmean(precision_c))
    recall       = float(np.nanmean(recall_c))
    f1_macro     = float(np.nanmean(f1))

    metrics = {
        "Pixel Acc": acc,
        "Balanced Acc": balanced_acc,
        "Precision": precision,
        "Recall": recall,
        "F1": f1_macro,
        "mIoU": mean_iu
    }

    for i in range(num_classes):
        metrics[f"IoU_Class_{i}"] = float(iu[i])
        metrics[f"F1_Class_{i}"] = float(f1[i])

    pd.DataFrame([metrics]).to_excel(os.path.join(train_dir, "Metrics.xlsx"), index=False)
    df_conf = pd.DataFrame(hist.astype(int),
        index=[f"GT_{i}" for i in range(num_classes)],
        columns=[f"Pred_{i}" for i in range(num_classes)]
    )
    df_conf.to_excel(os.path.join(train_dir, "Confusion.xlsx"))